name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        shell: bash
        working-directory: ${{ github.workspace }}

      - name: Build backend .env.prod file
        run: |
          echo 'DATABASE_URL=${{ secrets.DATABASE_URL }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'REDIS_HOST=${{ secrets.REDIS_HOST }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'REDIS_PORT=${{ secrets.REDIS_PORT }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'TAX_RECEIPT_TEMPLATE=${{ secrets.TAX_RECEIPT_TEMPLATE }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'TAX_RECEIPT_RELEASE_MONTH_INDEX=${{ secrets.TAX_RECEIPT_RELEASE_MONTH_INDEX }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'TAX_RECEIPT_RELEASE_DAY=${{ secrets.TAX_RECEIPT_RELEASE_DAY }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'DONOR_SYNC_ENABLED=${{ secrets.DONOR_SYNC_ENABLED }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'DONOR_SYNC_USERNAME=${{ secrets.DONOR_SYNC_USERNAME }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'DONOR_SYNC_PASSWORD=${{ secrets.DONOR_SYNC_PASSWORD }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'EMAIL_ENABLED=${{ secrets.EMAIL_ENABLED }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'EMAIL_TEST_MODE=${{ secrets.EMAIL_TEST_MODE }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'EMAIL_TEMPLATE_STORAGE_KEY=${{ secrets.EMAIL_TEMPLATE_STORAGE_KEY }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'SMTP_USER=${{ secrets.SMTP_USER }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'SMTP_SENDER=${{ secrets.SMTP_SENDER }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'SMTP_PASS=${{ secrets.SMTP_PASS }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'SMTP_REPLY_TO=${{ secrets.SMTP_REPLY_TO }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'AUTH_ENABLED=${{ secrets.AUTH_ENABLED }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'JWT_SECRET=${{ secrets.JWT_SECRET }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'JWT_TOKEN_LIFETIME_MS=${{ secrets.JWT_TOKEN_LIFETIME_MS }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'JWT_REFRESH_TOKEN_LIFETIME_MS=${{ secrets.JWT_REFRESH_TOKEN_LIFETIME_MS }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'REFRESH_TOKEN_COOKIE_PATH=${{ secrets.REFRESH_TOKEN_COOKIE_PATH }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'LOGTAIL_SOURCE_TOKEN=${{ secrets.LOGTAIL_SOURCE_TOKEN }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'LOGTAIL_INGESTING_HOST=${{ secrets.LOGTAIL_INGESTING_HOST }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'GCS_BUCKET_NAME=${{ secrets.GCS_BUCKET_NAME }}' >> ${{ github.workspace }}/dms-api/.env.prod
          echo 'GCS_BACKUP_BUCKET_NAME=${{ secrets.GCS_BACKUP_BUCKET_NAME }}' >> ${{ github.workspace }}/dms-api/.env.prod
        shell: bash
        
      - name: Build frontend .env.prod file
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> ${{ github.workspace }}/dms-frontend/.env.production
          echo "VITE_MOCK_API_HOST=${{ secrets.VITE_MOCK_API_HOST }}" >> ${{ github.workspace }}/dms-frontend/.env.production
          echo "VITE_AUTH_ENABLED=${{ secrets.VITE_AUTH_ENABLED }}" >> ${{ github.workspace }}/dms-frontend/.env.production
          echo "VITE_DONOR_EXTERNAL_PROVIDER_ENABLED=${{ secrets.VITE_DONOR_EXTERNAL_PROVIDER_ENABLED }}" >> ${{ github.workspace }}/dms-frontend/.env.production
          echo "VITE_DONOR_EXTERNAL_PROVIDER_NAME=${{ secrets.VITE_DONOR_EXTERNAL_PROVIDER_NAME }}" >> ${{ github.workspace }}/dms-frontend/.env.production
          echo "VITE_DONOR_EXTERNAL_PROVIDER_URL=${{ secrets.VITE_DONOR_EXTERNAL_PROVIDER_URL }}" >> ${{ github.workspace }}/dms-frontend/.env.production
        shell: bash

      - name: Create serviceAccount.json
        run: |
            echo "${{ secrets.SERVICE_ACCOUNT_JSON_BASE64 }}" | base64 --decode > ${{ github.workspace }}/dms-api/serviceAccount.json

      - name: Generate Prisma client
        run: DOTENV_CONFIG_PATH=${{ github.workspace }}/dms-api/.env.prod npx prisma generate --sql
        shell: bash
        working-directory: ${{ github.workspace }}/dms-api

      - name: Run tests
        run: npm run test:prod
        shell: bash
        working-directory: ${{ github.workspace }}

      - name: Upload Cypress screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: dms-frontend/cypress/screenshots

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add VPS to known_hosts
        run: ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Copy project to VPS
        run: |
          rsync -avz --exclude='.git' --exclude='node_modules' --exclude='**/node_modules' ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_PATH }}

      - name: Deploy with docker-compose
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd ${{ secrets.VPS_PATH }} && docker-compose -f docker-compose.prod.yml down && docker-compose -f docker-compose.prod.yml pull && docker-compose -f docker-compose.prod.yml up -d --remove-orphans"
